version: '3.1'

services:

  ghostV4:
    image: ghost:4-alpine
    restart: always
    ports:
      - 3004:2368
    environment:
      NODE_ENV: development
      
  ghostV3:
    image: ghost:3-alpine
    restart: always
    ports:
      - 3003:2368
    environment:
      NODE_ENV: development